### YamlMime:Yaml
ms.openlocfilehash: 32819343100f4d8212e660497c1dd9a1e652711a
ms.sourcegitcommit: 6ba4cafffd53c85f6f022afe7e28825d9b0797a4
ms.translationtype: HT
ms.contentlocale: ja-JP
ms.lasthandoff: 11/29/2021
ms.locfileid: "133213710"
parameters:
  buildConfiguration: Release
steps:
- task: DotNetCoreCLI@2
  displayName: Build the project - ${{ parameters.buildConfiguration }}
  inputs:
    command: build
    arguments: --no-restore --configuration ${{ parameters.buildConfiguration }}
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  displayName: Publish the project - ${{ parameters.buildConfiguration }}
  inputs:
    command: publish
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: --no-build --configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)/${{ parameters.buildConfiguration }}
    zipAfterPublish: true
